version: "3.9"
services:
  gui-app:
    container_name: sfml-gui

    image: localhost/sfml-gui:latest

    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/tmp/.Xauthority
      - WAYLAND_DISPLAY=wayland-0
      - XDG_RUNTIME_DIR=/run/user/1000
      - PULSE_SERVER=unix:/tmp/pulse
    
    # X11 socket, data volume, and PulseAudio socket
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - sfml-data:/comp4-grading
      - /run/user/1000/pulse/native:/tmp/pulse
    
    # GPU
    devices:
      - /dev/dri:/dev/dri

    network_mode: "host"
    tty: true
  
volumes:
  sfml-data:
    driver: local
