version: "3.9"
services:
  gui-app:
    container_name: sfml-gui

    image: localhost/sfml-gui:latest

    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=${XAUTHORITY}
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      # - XDG_RUNTIME_DIR=/run/user/1000            # Uncomment if on Linux with X11 auth
      - XDG_RUNTIME_DIR=/tmp/runtime-dir            # For WSLg, comment if on Linux
      - PULSE_SERVER=unix:/tmp/pulse
    
    # X11 socket, data volume, and PulseAudio socket
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - sfml-data:/comp4-grading
      # - /run/user/1000/pulse/native:/tmp/pulse    # Uncomment if using PulseAudio on Linux
      # - ${XAUTHORITY}:${XAUTHORITY}:ro            # Uncomment if on Linux with X11 auth
      - /mnt/wslg/pulse/native:/tmp/pulse:ro        # For PulseAudio in WSLg, comment if on Linux
      - /mnt/wslg/runtime-dir:/tmp/runtime-dir      # Comment out if on Linux
    
    # GPU
    devices:
      # - /dev/dri:/dev/dri                         # Uncomment if on Linux with direct GPU access
      - /dev/dxg:/dev/dxg                           # For WSLg GPU access, comment if on Linux

    network_mode: "host"
    tty: true
  
volumes:
  sfml-data:
    driver: local
